<?php
/**
 * SettlementApi
 * PHP version 7.4
 *
 * @category Class
 * @package  Pensopay\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payment API
 *
 * Create and manage your Payments
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@pensopay.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Pensopay\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Pensopay\Client\ApiException;
use Pensopay\Client\Configuration;
use Pensopay\Client\HeaderSelector;
use Pensopay\Client\ObjectSerializer;

/**
 * SettlementApi Class Doc Comment
 *
 * @category Class
 * @package  Pensopay\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SettlementApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getSettlement' => [
            'application/json',
        ],
        'getSettlements' => [
            'application/json',
        ],
        'getTransactionsBySettlement' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getSettlement
     *
     * Get Settlement
     *
     * @param  string $settlement_id Settlement ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSettlement'] to see the possible values for this operation
     *
     * @throws \Pensopay\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Pensopay\Client\Model\SettlementResponse
     */
    public function getSettlement($settlement_id, string $contentType = self::contentTypes['getSettlement'][0])
    {
        list($response) = $this->getSettlementWithHttpInfo($settlement_id, $contentType);
        return $response;
    }

    /**
     * Operation getSettlementWithHttpInfo
     *
     * Get Settlement
     *
     * @param  string $settlement_id Settlement ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSettlement'] to see the possible values for this operation
     *
     * @throws \Pensopay\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Pensopay\Client\Model\SettlementResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSettlementWithHttpInfo($settlement_id, string $contentType = self::contentTypes['getSettlement'][0])
    {
        $request = $this->getSettlementRequest($settlement_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Pensopay\Client\Model\SettlementResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Pensopay\Client\Model\SettlementResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Pensopay\Client\Model\SettlementResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Pensopay\Client\Model\SettlementResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Pensopay\Client\Model\SettlementResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getSettlementAsync
     *
     * Get Settlement
     *
     * @param  string $settlement_id Settlement ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSettlement'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSettlementAsync($settlement_id, string $contentType = self::contentTypes['getSettlement'][0])
    {
        return $this->getSettlementAsyncWithHttpInfo($settlement_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSettlementAsyncWithHttpInfo
     *
     * Get Settlement
     *
     * @param  string $settlement_id Settlement ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSettlement'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSettlementAsyncWithHttpInfo($settlement_id, string $contentType = self::contentTypes['getSettlement'][0])
    {
        $returnType = '\Pensopay\Client\Model\SettlementResponse';
        $request = $this->getSettlementRequest($settlement_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getSettlement'
     *
     * @param  string $settlement_id Settlement ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSettlement'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getSettlementRequest($settlement_id, string $contentType = self::contentTypes['getSettlement'][0])
    {

        // verify the required parameter 'settlement_id' is set
        if ($settlement_id === null || (is_array($settlement_id) && count($settlement_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $settlement_id when calling getSettlement'
            );
        }


        $resourcePath = '/settlements/{settlementId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($settlement_id !== null) {
            $resourcePath = str_replace(
                '{' . 'settlementId' . '}',
                ObjectSerializer::toPathValue($settlement_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getSettlements
     *
     * Get settlements
     *
     * @param  int $per_page How many results to list per page between 1 and 100. (optional, default to 10)
     * @param  int $page What page to view (optional, default to 1)
     * @param  bool $settled Filter by settled status, true or false. (optional)
     * @param  string $currency Currency Code (ISO-4217). (optional)
     * @param  string $date_from Find settlements with payout date after or during date_from. Takes an ISO-8601 date string. (optional)
     * @param  string $date_to Find settlements with payout date before or during date_to. Takes an ISO-8601 date string. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSettlements'] to see the possible values for this operation
     *
     * @throws \Pensopay\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Pensopay\Client\Model\SettlementsResponse
     */
    public function getSettlements($per_page = 10, $page = 1, $settled = null, $currency = null, $date_from = null, $date_to = null, string $contentType = self::contentTypes['getSettlements'][0])
    {
        list($response) = $this->getSettlementsWithHttpInfo($per_page, $page, $settled, $currency, $date_from, $date_to, $contentType);
        return $response;
    }

    /**
     * Operation getSettlementsWithHttpInfo
     *
     * Get settlements
     *
     * @param  int $per_page How many results to list per page between 1 and 100. (optional, default to 10)
     * @param  int $page What page to view (optional, default to 1)
     * @param  bool $settled Filter by settled status, true or false. (optional)
     * @param  string $currency Currency Code (ISO-4217). (optional)
     * @param  string $date_from Find settlements with payout date after or during date_from. Takes an ISO-8601 date string. (optional)
     * @param  string $date_to Find settlements with payout date before or during date_to. Takes an ISO-8601 date string. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSettlements'] to see the possible values for this operation
     *
     * @throws \Pensopay\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Pensopay\Client\Model\SettlementsResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSettlementsWithHttpInfo($per_page = 10, $page = 1, $settled = null, $currency = null, $date_from = null, $date_to = null, string $contentType = self::contentTypes['getSettlements'][0])
    {
        $request = $this->getSettlementsRequest($per_page, $page, $settled, $currency, $date_from, $date_to, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Pensopay\Client\Model\SettlementsResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Pensopay\Client\Model\SettlementsResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Pensopay\Client\Model\SettlementsResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Pensopay\Client\Model\SettlementsResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Pensopay\Client\Model\SettlementsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getSettlementsAsync
     *
     * Get settlements
     *
     * @param  int $per_page How many results to list per page between 1 and 100. (optional, default to 10)
     * @param  int $page What page to view (optional, default to 1)
     * @param  bool $settled Filter by settled status, true or false. (optional)
     * @param  string $currency Currency Code (ISO-4217). (optional)
     * @param  string $date_from Find settlements with payout date after or during date_from. Takes an ISO-8601 date string. (optional)
     * @param  string $date_to Find settlements with payout date before or during date_to. Takes an ISO-8601 date string. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSettlements'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSettlementsAsync($per_page = 10, $page = 1, $settled = null, $currency = null, $date_from = null, $date_to = null, string $contentType = self::contentTypes['getSettlements'][0])
    {
        return $this->getSettlementsAsyncWithHttpInfo($per_page, $page, $settled, $currency, $date_from, $date_to, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSettlementsAsyncWithHttpInfo
     *
     * Get settlements
     *
     * @param  int $per_page How many results to list per page between 1 and 100. (optional, default to 10)
     * @param  int $page What page to view (optional, default to 1)
     * @param  bool $settled Filter by settled status, true or false. (optional)
     * @param  string $currency Currency Code (ISO-4217). (optional)
     * @param  string $date_from Find settlements with payout date after or during date_from. Takes an ISO-8601 date string. (optional)
     * @param  string $date_to Find settlements with payout date before or during date_to. Takes an ISO-8601 date string. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSettlements'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSettlementsAsyncWithHttpInfo($per_page = 10, $page = 1, $settled = null, $currency = null, $date_from = null, $date_to = null, string $contentType = self::contentTypes['getSettlements'][0])
    {
        $returnType = '\Pensopay\Client\Model\SettlementsResponse';
        $request = $this->getSettlementsRequest($per_page, $page, $settled, $currency, $date_from, $date_to, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getSettlements'
     *
     * @param  int $per_page How many results to list per page between 1 and 100. (optional, default to 10)
     * @param  int $page What page to view (optional, default to 1)
     * @param  bool $settled Filter by settled status, true or false. (optional)
     * @param  string $currency Currency Code (ISO-4217). (optional)
     * @param  string $date_from Find settlements with payout date after or during date_from. Takes an ISO-8601 date string. (optional)
     * @param  string $date_to Find settlements with payout date before or during date_to. Takes an ISO-8601 date string. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSettlements'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getSettlementsRequest($per_page = 10, $page = 1, $settled = null, $currency = null, $date_from = null, $date_to = null, string $contentType = self::contentTypes['getSettlements'][0])
    {








        $resourcePath = '/settlements';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $per_page,
            'per_page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $settled,
            'settled', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $currency,
            'currency', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $date_from,
            'date_from', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $date_to,
            'date_to', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getTransactionsBySettlement
     *
     * Get Settlement Transactions
     *
     * @param  string $settlement_id Settlement ID (required)
     * @param  int $per_page How many results to list per page between 1 and 100. (optional, default to 10)
     * @param  int $page What page to view (optional, default to 1)
     * @param  string $is Filter by transaction type. (optional)
     * @param  string $currency Currency Code (ISO-4217). (optional)
     * @param  string $status The status of the transaction (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTransactionsBySettlement'] to see the possible values for this operation
     *
     * @throws \Pensopay\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Pensopay\Client\Model\TransactionsResponse
     */
    public function getTransactionsBySettlement($settlement_id, $per_page = 10, $page = 1, $is = null, $currency = null, $status = null, string $contentType = self::contentTypes['getTransactionsBySettlement'][0])
    {
        list($response) = $this->getTransactionsBySettlementWithHttpInfo($settlement_id, $per_page, $page, $is, $currency, $status, $contentType);
        return $response;
    }

    /**
     * Operation getTransactionsBySettlementWithHttpInfo
     *
     * Get Settlement Transactions
     *
     * @param  string $settlement_id Settlement ID (required)
     * @param  int $per_page How many results to list per page between 1 and 100. (optional, default to 10)
     * @param  int $page What page to view (optional, default to 1)
     * @param  string $is Filter by transaction type. (optional)
     * @param  string $currency Currency Code (ISO-4217). (optional)
     * @param  string $status The status of the transaction (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTransactionsBySettlement'] to see the possible values for this operation
     *
     * @throws \Pensopay\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Pensopay\Client\Model\TransactionsResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getTransactionsBySettlementWithHttpInfo($settlement_id, $per_page = 10, $page = 1, $is = null, $currency = null, $status = null, string $contentType = self::contentTypes['getTransactionsBySettlement'][0])
    {
        $request = $this->getTransactionsBySettlementRequest($settlement_id, $per_page, $page, $is, $currency, $status, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Pensopay\Client\Model\TransactionsResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Pensopay\Client\Model\TransactionsResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Pensopay\Client\Model\TransactionsResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Pensopay\Client\Model\TransactionsResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Pensopay\Client\Model\TransactionsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getTransactionsBySettlementAsync
     *
     * Get Settlement Transactions
     *
     * @param  string $settlement_id Settlement ID (required)
     * @param  int $per_page How many results to list per page between 1 and 100. (optional, default to 10)
     * @param  int $page What page to view (optional, default to 1)
     * @param  string $is Filter by transaction type. (optional)
     * @param  string $currency Currency Code (ISO-4217). (optional)
     * @param  string $status The status of the transaction (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTransactionsBySettlement'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTransactionsBySettlementAsync($settlement_id, $per_page = 10, $page = 1, $is = null, $currency = null, $status = null, string $contentType = self::contentTypes['getTransactionsBySettlement'][0])
    {
        return $this->getTransactionsBySettlementAsyncWithHttpInfo($settlement_id, $per_page, $page, $is, $currency, $status, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getTransactionsBySettlementAsyncWithHttpInfo
     *
     * Get Settlement Transactions
     *
     * @param  string $settlement_id Settlement ID (required)
     * @param  int $per_page How many results to list per page between 1 and 100. (optional, default to 10)
     * @param  int $page What page to view (optional, default to 1)
     * @param  string $is Filter by transaction type. (optional)
     * @param  string $currency Currency Code (ISO-4217). (optional)
     * @param  string $status The status of the transaction (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTransactionsBySettlement'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTransactionsBySettlementAsyncWithHttpInfo($settlement_id, $per_page = 10, $page = 1, $is = null, $currency = null, $status = null, string $contentType = self::contentTypes['getTransactionsBySettlement'][0])
    {
        $returnType = '\Pensopay\Client\Model\TransactionsResponse';
        $request = $this->getTransactionsBySettlementRequest($settlement_id, $per_page, $page, $is, $currency, $status, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getTransactionsBySettlement'
     *
     * @param  string $settlement_id Settlement ID (required)
     * @param  int $per_page How many results to list per page between 1 and 100. (optional, default to 10)
     * @param  int $page What page to view (optional, default to 1)
     * @param  string $is Filter by transaction type. (optional)
     * @param  string $currency Currency Code (ISO-4217). (optional)
     * @param  string $status The status of the transaction (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTransactionsBySettlement'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getTransactionsBySettlementRequest($settlement_id, $per_page = 10, $page = 1, $is = null, $currency = null, $status = null, string $contentType = self::contentTypes['getTransactionsBySettlement'][0])
    {

        // verify the required parameter 'settlement_id' is set
        if ($settlement_id === null || (is_array($settlement_id) && count($settlement_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $settlement_id when calling getTransactionsBySettlement'
            );
        }







        $resourcePath = '/settlements/{settlementId}/transactions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $per_page,
            'per_page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $is,
            'is', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $currency,
            'currency', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $status,
            'status', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($settlement_id !== null) {
            $resourcePath = str_replace(
                '{' . 'settlementId' . '}',
                ObjectSerializer::toPathValue($settlement_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
