<?php
/**
 * PaymentCreatePaymentRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Pensopay\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payment API
 *
 * Create and manage your Payments
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@pensopay.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Pensopay\Client\Model;

use \ArrayAccess;
use \Pensopay\Client\ObjectSerializer;

/**
 * PaymentCreatePaymentRequest Class Doc Comment
 *
 * @category Class
 * @package  Pensopay\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PaymentCreatePaymentRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'payment.CreatePaymentRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'amount' => 'int',
        'autocapture' => 'bool',
        'branding_id' => 'string',
        'callback_url' => 'string',
        'cancel_url' => 'string',
        'currency' => 'string',
        'locale' => 'string',
        'methods' => 'string[]',
        'order' => '\Pensopay\Client\Model\PaymentPaymentOrder',
        'order_id' => 'string',
        'success_url' => 'string',
        'testmode' => 'bool',
        'variables' => 'array<string,string>',
        'branding_uuid' => 'string',
        'text_on_statement' => 'string',
        'expires_in' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'amount' => null,
        'autocapture' => null,
        'branding_id' => null,
        'callback_url' => 'uri',
        'cancel_url' => 'uri',
        'currency' => null,
        'locale' => null,
        'methods' => null,
        'order' => null,
        'order_id' => null,
        'success_url' => 'uri',
        'testmode' => null,
        'variables' => null,
        'branding_uuid' => null,
        'text_on_statement' => null,
        'expires_in' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'amount' => false,
        'autocapture' => false,
        'branding_id' => false,
        'callback_url' => false,
        'cancel_url' => false,
        'currency' => false,
        'locale' => false,
        'methods' => false,
        'order' => false,
        'order_id' => false,
        'success_url' => false,
        'testmode' => false,
        'variables' => false,
        'branding_uuid' => false,
        'text_on_statement' => false,
        'expires_in' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'amount' => 'amount',
        'autocapture' => 'autocapture',
        'branding_id' => 'branding_id',
        'callback_url' => 'callback_url',
        'cancel_url' => 'cancel_url',
        'currency' => 'currency',
        'locale' => 'locale',
        'methods' => 'methods',
        'order' => 'order',
        'order_id' => 'order_id',
        'success_url' => 'success_url',
        'testmode' => 'testmode',
        'variables' => 'variables',
        'branding_uuid' => 'branding_uuid',
        'text_on_statement' => 'text_on_statement',
        'expires_in' => 'expires_in'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'amount' => 'setAmount',
        'autocapture' => 'setAutocapture',
        'branding_id' => 'setBrandingId',
        'callback_url' => 'setCallbackUrl',
        'cancel_url' => 'setCancelUrl',
        'currency' => 'setCurrency',
        'locale' => 'setLocale',
        'methods' => 'setMethods',
        'order' => 'setOrder',
        'order_id' => 'setOrderId',
        'success_url' => 'setSuccessUrl',
        'testmode' => 'setTestmode',
        'variables' => 'setVariables',
        'branding_uuid' => 'setBrandingUuid',
        'text_on_statement' => 'setTextOnStatement',
        'expires_in' => 'setExpiresIn'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'amount' => 'getAmount',
        'autocapture' => 'getAutocapture',
        'branding_id' => 'getBrandingId',
        'callback_url' => 'getCallbackUrl',
        'cancel_url' => 'getCancelUrl',
        'currency' => 'getCurrency',
        'locale' => 'getLocale',
        'methods' => 'getMethods',
        'order' => 'getOrder',
        'order_id' => 'getOrderId',
        'success_url' => 'getSuccessUrl',
        'testmode' => 'getTestmode',
        'variables' => 'getVariables',
        'branding_uuid' => 'getBrandingUuid',
        'text_on_statement' => 'getTextOnStatement',
        'expires_in' => 'getExpiresIn'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const METHODS_CARD = 'card';
    public const METHODS_DANKORT = 'dankort';
    public const METHODS_MASTERCARD = 'mastercard';
    public const METHODS_VISA = 'visa';
    public const METHODS_VISADEBIT = 'visadebit';
    public const METHODS_VISAELECTRON = 'visaelectron';
    public const METHODS_MASTERCARDDEBIT = 'mastercarddebit';
    public const METHODS_WALLET = 'wallet';
    public const METHODS_MOBILEPAY = 'mobilepay';
    public const METHODS_VIPPSPSP = 'vippspsp';
    public const METHODS_APPLEPAY = 'applepay';
    public const METHODS_GOOGLEPAY = 'googlepay';
    public const METHODS_PAYLATER = 'paylater';
    public const METHODS_ANYDAY = 'anyday';
    public const METHODS_VIABILL = 'viabill';
    public const METHODS_BANKTRANSFER = 'banktransfer';
    public const METHODS_SWISH = 'swish';
    public const METHODS_THIRDPARTY = 'thirdparty';
    public const METHODS_PAYPAL = 'paypal';
    public const METHODS_KLARNA = 'klarna';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getMethodsAllowableValues()
    {
        return [
            self::METHODS_CARD,
            self::METHODS_DANKORT,
            self::METHODS_MASTERCARD,
            self::METHODS_VISA,
            self::METHODS_VISADEBIT,
            self::METHODS_VISAELECTRON,
            self::METHODS_MASTERCARDDEBIT,
            self::METHODS_WALLET,
            self::METHODS_MOBILEPAY,
            self::METHODS_VIPPSPSP,
            self::METHODS_APPLEPAY,
            self::METHODS_GOOGLEPAY,
            self::METHODS_PAYLATER,
            self::METHODS_ANYDAY,
            self::METHODS_VIABILL,
            self::METHODS_BANKTRANSFER,
            self::METHODS_SWISH,
            self::METHODS_THIRDPARTY,
            self::METHODS_PAYPAL,
            self::METHODS_KLARNA,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('autocapture', $data ?? [], null);
        $this->setIfExists('branding_id', $data ?? [], null);
        $this->setIfExists('callback_url', $data ?? [], null);
        $this->setIfExists('cancel_url', $data ?? [], null);
        $this->setIfExists('currency', $data ?? [], null);
        $this->setIfExists('locale', $data ?? [], null);
        $this->setIfExists('methods', $data ?? [], null);
        $this->setIfExists('order', $data ?? [], null);
        $this->setIfExists('order_id', $data ?? [], null);
        $this->setIfExists('success_url', $data ?? [], null);
        $this->setIfExists('testmode', $data ?? [], null);
        $this->setIfExists('variables', $data ?? [], null);
        $this->setIfExists('branding_uuid', $data ?? [], null);
        $this->setIfExists('text_on_statement', $data ?? [], null);
        $this->setIfExists('expires_in', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['amount'] === null) {
            $invalidProperties[] = "'amount' can't be null";
        }
        if (($this->container['amount'] < 1)) {
            $invalidProperties[] = "invalid value for 'amount', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['callback_url']) && !preg_match("/^https:\/\//", $this->container['callback_url'])) {
            $invalidProperties[] = "invalid value for 'callback_url', must be conform to the pattern /^https:\/\//.";
        }

        if (!is_null($this->container['cancel_url']) && !preg_match("/^https:\/\//", $this->container['cancel_url'])) {
            $invalidProperties[] = "invalid value for 'cancel_url', must be conform to the pattern /^https:\/\//.";
        }

        if ($this->container['currency'] === null) {
            $invalidProperties[] = "'currency' can't be null";
        }
        if (!is_null($this->container['locale']) && (mb_strlen($this->container['locale']) > 5)) {
            $invalidProperties[] = "invalid value for 'locale', the character length must be smaller than or equal to 5.";
        }

        if (!is_null($this->container['locale']) && (mb_strlen($this->container['locale']) < 5)) {
            $invalidProperties[] = "invalid value for 'locale', the character length must be bigger than or equal to 5.";
        }

        if ($this->container['order_id'] === null) {
            $invalidProperties[] = "'order_id' can't be null";
        }
        if ((mb_strlen($this->container['order_id']) > 36)) {
            $invalidProperties[] = "invalid value for 'order_id', the character length must be smaller than or equal to 36.";
        }

        if ((mb_strlen($this->container['order_id']) < 1)) {
            $invalidProperties[] = "invalid value for 'order_id', the character length must be bigger than or equal to 1.";
        }

        if (!preg_match("/^[a-zA-Z0-9_\\-]*$/", $this->container['order_id'])) {
            $invalidProperties[] = "invalid value for 'order_id', must be conform to the pattern /^[a-zA-Z0-9_\\-]*$/.";
        }

        if (!is_null($this->container['success_url']) && !preg_match("/^https:\/\//", $this->container['success_url'])) {
            $invalidProperties[] = "invalid value for 'success_url', must be conform to the pattern /^https:\/\//.";
        }

        if (!is_null($this->container['text_on_statement']) && (mb_strlen($this->container['text_on_statement']) > 22)) {
            $invalidProperties[] = "invalid value for 'text_on_statement', the character length must be smaller than or equal to 22.";
        }

        if (!is_null($this->container['text_on_statement']) && (mb_strlen($this->container['text_on_statement']) < 2)) {
            $invalidProperties[] = "invalid value for 'text_on_statement', the character length must be bigger than or equal to 2.";
        }

        if (!is_null($this->container['text_on_statement']) && !preg_match("/^[\\x20-\\x7E]*$/", $this->container['text_on_statement'])) {
            $invalidProperties[] = "invalid value for 'text_on_statement', must be conform to the pattern /^[\\x20-\\x7E]*$/.";
        }

        if (!is_null($this->container['expires_in']) && ($this->container['expires_in'] < 0)) {
            $invalidProperties[] = "invalid value for 'expires_in', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets amount
     *
     * @return int
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param int $amount The amount in currency's lowest denominator
     *
     * @return self
     */
    public function setAmount($amount)
    {
        if (is_null($amount)) {
            throw new \InvalidArgumentException('non-nullable amount cannot be null');
        }

        if (($amount < 1)) {
            throw new \InvalidArgumentException('invalid value for $amount when calling PaymentCreatePaymentRequest., must be bigger than or equal to 1.');
        }

        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets autocapture
     *
     * @return bool|null
     */
    public function getAutocapture()
    {
        return $this->container['autocapture'];
    }

    /**
     * Sets autocapture
     *
     * @param bool|null $autocapture autocapture
     *
     * @return self
     */
    public function setAutocapture($autocapture)
    {
        if (is_null($autocapture)) {
            throw new \InvalidArgumentException('non-nullable autocapture cannot be null');
        }
        $this->container['autocapture'] = $autocapture;

        return $this;
    }

    /**
     * Gets branding_id
     *
     * @return string|null
     */
    public function getBrandingId()
    {
        return $this->container['branding_id'];
    }

    /**
     * Sets branding_id
     *
     * @param string|null $branding_id branding_id
     *
     * @return self
     */
    public function setBrandingId($branding_id)
    {
        if (is_null($branding_id)) {
            throw new \InvalidArgumentException('non-nullable branding_id cannot be null');
        }
        $this->container['branding_id'] = $branding_id;

        return $this;
    }

    /**
     * Gets callback_url
     *
     * @return string|null
     */
    public function getCallbackUrl()
    {
        return $this->container['callback_url'];
    }

    /**
     * Sets callback_url
     *
     * @param string|null $callback_url callback_url
     *
     * @return self
     */
    public function setCallbackUrl($callback_url)
    {
        if (is_null($callback_url)) {
            throw new \InvalidArgumentException('non-nullable callback_url cannot be null');
        }

        if ((!preg_match("/^https:\/\//", ObjectSerializer::toString($callback_url)))) {
            throw new \InvalidArgumentException("invalid value for \$callback_url when calling PaymentCreatePaymentRequest., must conform to the pattern /^https:\/\//.");
        }

        $this->container['callback_url'] = $callback_url;

        return $this;
    }

    /**
     * Gets cancel_url
     *
     * @return string|null
     */
    public function getCancelUrl()
    {
        return $this->container['cancel_url'];
    }

    /**
     * Sets cancel_url
     *
     * @param string|null $cancel_url cancel_url
     *
     * @return self
     */
    public function setCancelUrl($cancel_url)
    {
        if (is_null($cancel_url)) {
            throw new \InvalidArgumentException('non-nullable cancel_url cannot be null');
        }

        if ((!preg_match("/^https:\/\//", ObjectSerializer::toString($cancel_url)))) {
            throw new \InvalidArgumentException("invalid value for \$cancel_url when calling PaymentCreatePaymentRequest., must conform to the pattern /^https:\/\//.");
        }

        $this->container['cancel_url'] = $cancel_url;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return string
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param string $currency The currency in ISO 4217 format
     *
     * @return self
     */
    public function setCurrency($currency)
    {
        if (is_null($currency)) {
            throw new \InvalidArgumentException('non-nullable currency cannot be null');
        }
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets locale
     *
     * @return string|null
     */
    public function getLocale()
    {
        return $this->container['locale'];
    }

    /**
     * Sets locale
     *
     * @param string|null $locale Locale to use in payment window
     *
     * @return self
     */
    public function setLocale($locale)
    {
        if (is_null($locale)) {
            throw new \InvalidArgumentException('non-nullable locale cannot be null');
        }
        if ((mb_strlen($locale) > 5)) {
            throw new \InvalidArgumentException('invalid length for $locale when calling PaymentCreatePaymentRequest., must be smaller than or equal to 5.');
        }
        if ((mb_strlen($locale) < 5)) {
            throw new \InvalidArgumentException('invalid length for $locale when calling PaymentCreatePaymentRequest., must be bigger than or equal to 5.');
        }

        $this->container['locale'] = $locale;

        return $this;
    }

    /**
     * Gets methods
     *
     * @return string[]|null
     */
    public function getMethods()
    {
        return $this->container['methods'];
    }

    /**
     * Sets methods
     *
     * @param string[]|null $methods The following payment methods can be defined as available when creating the payment. _Ex._ if `[\"card\"]` is sent all available card methods for the account will be available.  **card** - dankort - mastercard - visa - visadebit / visaelectron - mastercarddebit  **wallet** - mobilepay - vippspsp - googlepay - applepay  **paylater** - anyday - viabill  **thirdparty** - paypal - klarna  **banktransfer** - swish
     *
     * @return self
     */
    public function setMethods($methods)
    {
        if (is_null($methods)) {
            throw new \InvalidArgumentException('non-nullable methods cannot be null');
        }
        $allowedValues = $this->getMethodsAllowableValues();
        if (array_diff($methods, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'methods', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['methods'] = $methods;

        return $this;
    }

    /**
     * Gets order
     *
     * @return \Pensopay\Client\Model\PaymentPaymentOrder|null
     */
    public function getOrder()
    {
        return $this->container['order'];
    }

    /**
     * Sets order
     *
     * @param \Pensopay\Client\Model\PaymentPaymentOrder|null $order order
     *
     * @return self
     */
    public function setOrder($order)
    {
        if (is_null($order)) {
            throw new \InvalidArgumentException('non-nullable order cannot be null');
        }
        $this->container['order'] = $order;

        return $this;
    }

    /**
     * Gets order_id
     *
     * @return string
     */
    public function getOrderId()
    {
        return $this->container['order_id'];
    }

    /**
     * Sets order_id
     *
     * @param string $order_id order_id
     *
     * @return self
     */
    public function setOrderId($order_id)
    {
        if (is_null($order_id)) {
            throw new \InvalidArgumentException('non-nullable order_id cannot be null');
        }
        if ((mb_strlen($order_id) > 36)) {
            throw new \InvalidArgumentException('invalid length for $order_id when calling PaymentCreatePaymentRequest., must be smaller than or equal to 36.');
        }
        if ((mb_strlen($order_id) < 1)) {
            throw new \InvalidArgumentException('invalid length for $order_id when calling PaymentCreatePaymentRequest., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^[a-zA-Z0-9_\\-]*$/", ObjectSerializer::toString($order_id)))) {
            throw new \InvalidArgumentException("invalid value for \$order_id when calling PaymentCreatePaymentRequest., must conform to the pattern /^[a-zA-Z0-9_\\-]*$/.");
        }

        $this->container['order_id'] = $order_id;

        return $this;
    }

    /**
     * Gets success_url
     *
     * @return string|null
     */
    public function getSuccessUrl()
    {
        return $this->container['success_url'];
    }

    /**
     * Sets success_url
     *
     * @param string|null $success_url success_url
     *
     * @return self
     */
    public function setSuccessUrl($success_url)
    {
        if (is_null($success_url)) {
            throw new \InvalidArgumentException('non-nullable success_url cannot be null');
        }

        if ((!preg_match("/^https:\/\//", ObjectSerializer::toString($success_url)))) {
            throw new \InvalidArgumentException("invalid value for \$success_url when calling PaymentCreatePaymentRequest., must conform to the pattern /^https:\/\//.");
        }

        $this->container['success_url'] = $success_url;

        return $this;
    }

    /**
     * Gets testmode
     *
     * @return bool|null
     */
    public function getTestmode()
    {
        return $this->container['testmode'];
    }

    /**
     * Sets testmode
     *
     * @param bool|null $testmode testmode
     *
     * @return self
     */
    public function setTestmode($testmode)
    {
        if (is_null($testmode)) {
            throw new \InvalidArgumentException('non-nullable testmode cannot be null');
        }
        $this->container['testmode'] = $testmode;

        return $this;
    }

    /**
     * Gets variables
     *
     * @return array<string,string>|null
     */
    public function getVariables()
    {
        return $this->container['variables'];
    }

    /**
     * Sets variables
     *
     * @param array<string,string>|null $variables variables
     *
     * @return self
     */
    public function setVariables($variables)
    {
        if (is_null($variables)) {
            throw new \InvalidArgumentException('non-nullable variables cannot be null');
        }
        $this->container['variables'] = $variables;

        return $this;
    }

    /**
     * Gets branding_uuid
     *
     * @return string|null
     */
    public function getBrandingUuid()
    {
        return $this->container['branding_uuid'];
    }

    /**
     * Sets branding_uuid
     *
     * @param string|null $branding_uuid UUID of branding to use on payment window
     *
     * @return self
     */
    public function setBrandingUuid($branding_uuid)
    {
        if (is_null($branding_uuid)) {
            throw new \InvalidArgumentException('non-nullable branding_uuid cannot be null');
        }
        $this->container['branding_uuid'] = $branding_uuid;

        return $this;
    }

    /**
     * Gets text_on_statement
     *
     * @return string|null
     */
    public function getTextOnStatement()
    {
        return $this->container['text_on_statement'];
    }

    /**
     * Sets text_on_statement
     *
     * @param string|null $text_on_statement text_on_statement
     *
     * @return self
     */
    public function setTextOnStatement($text_on_statement)
    {
        if (is_null($text_on_statement)) {
            throw new \InvalidArgumentException('non-nullable text_on_statement cannot be null');
        }
        if ((mb_strlen($text_on_statement) > 22)) {
            throw new \InvalidArgumentException('invalid length for $text_on_statement when calling PaymentCreatePaymentRequest., must be smaller than or equal to 22.');
        }
        if ((mb_strlen($text_on_statement) < 2)) {
            throw new \InvalidArgumentException('invalid length for $text_on_statement when calling PaymentCreatePaymentRequest., must be bigger than or equal to 2.');
        }
        if ((!preg_match("/^[\\x20-\\x7E]*$/", ObjectSerializer::toString($text_on_statement)))) {
            throw new \InvalidArgumentException("invalid value for \$text_on_statement when calling PaymentCreatePaymentRequest., must conform to the pattern /^[\\x20-\\x7E]*$/.");
        }

        $this->container['text_on_statement'] = $text_on_statement;

        return $this;
    }

    /**
     * Gets expires_in
     *
     * @return int|null
     */
    public function getExpiresIn()
    {
        return $this->container['expires_in'];
    }

    /**
     * Sets expires_in
     *
     * @param int|null $expires_in Specify amount of seconds the payment will be available for the cardholder.
     *
     * @return self
     */
    public function setExpiresIn($expires_in)
    {
        if (is_null($expires_in)) {
            throw new \InvalidArgumentException('non-nullable expires_in cannot be null');
        }

        if (($expires_in < 0)) {
            throw new \InvalidArgumentException('invalid value for $expires_in when calling PaymentCreatePaymentRequest., must be bigger than or equal to 0.');
        }

        $this->container['expires_in'] = $expires_in;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


