<?php
/**
 * PaymentPaymentDetails
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Pensopay\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payment API
 *
 * Create and manage your Payments
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@pensopay.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Pensopay\Client\Model;

use \ArrayAccess;
use \Pensopay\Client\ObjectSerializer;

/**
 * PaymentPaymentDetails Class Doc Comment
 *
 * @category Class
 * @package  Pensopay\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PaymentPaymentDetails implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'payment.PaymentDetails';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        '_3dSecureType' => 'string',
        'acquirer' => 'string',
        'bin' => 'string',
        'brand' => 'string',
        'country' => 'string',
        'customerCountry' => 'string',
        'customerIp' => 'string',
        'expMonth' => 'string',
        'expYear' => 'string',
        'is3dSecure' => 'bool',
        'last4' => 'string',
        'method' => 'string',
        'segment' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        '_3dSecureType' => null,
        'acquirer' => null,
        'bin' => null,
        'brand' => null,
        'country' => null,
        'customerCountry' => null,
        'customerIp' => null,
        'expMonth' => null,
        'expYear' => null,
        'is3dSecure' => null,
        'last4' => null,
        'method' => null,
        'segment' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        '_3dSecureType' => false,
        'acquirer' => false,
        'bin' => false,
        'brand' => false,
        'country' => false,
        'customerCountry' => false,
        'customerIp' => false,
        'expMonth' => false,
        'expYear' => false,
        'is3dSecure' => false,
        'last4' => false,
        'method' => false,
        'segment' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        '_3dSecureType' => '3d_secure_type',
        'acquirer' => 'acquirer',
        'bin' => 'bin',
        'brand' => 'brand',
        'country' => 'country',
        'customerCountry' => 'customer_country',
        'customerIp' => 'customer_ip',
        'expMonth' => 'exp_month',
        'expYear' => 'exp_year',
        'is3dSecure' => 'is_3d_secure',
        'last4' => 'last4',
        'method' => 'method',
        'segment' => 'segment'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        '_3dSecureType' => 'set3dSecureType',
        'acquirer' => 'setAcquirer',
        'bin' => 'setBin',
        'brand' => 'setBrand',
        'country' => 'setCountry',
        'customerCountry' => 'setCustomerCountry',
        'customerIp' => 'setCustomerIp',
        'expMonth' => 'setExpMonth',
        'expYear' => 'setExpYear',
        'is3dSecure' => 'setIs3dSecure',
        'last4' => 'setLast4',
        'method' => 'setMethod',
        'segment' => 'setSegment'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        '_3dSecureType' => 'get3dSecureType',
        'acquirer' => 'getAcquirer',
        'bin' => 'getBin',
        'brand' => 'getBrand',
        'country' => 'getCountry',
        'customerCountry' => 'getCustomerCountry',
        'customerIp' => 'getCustomerIp',
        'expMonth' => 'getExpMonth',
        'expYear' => 'getExpYear',
        'is3dSecure' => 'getIs3dSecure',
        'last4' => 'getLast4',
        'method' => 'getMethod',
        'segment' => 'getSegment'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('_3dSecureType', $data ?? [], null);
        $this->setIfExists('acquirer', $data ?? [], null);
        $this->setIfExists('bin', $data ?? [], null);
        $this->setIfExists('brand', $data ?? [], null);
        $this->setIfExists('country', $data ?? [], null);
        $this->setIfExists('customerCountry', $data ?? [], null);
        $this->setIfExists('customerIp', $data ?? [], null);
        $this->setIfExists('expMonth', $data ?? [], null);
        $this->setIfExists('expYear', $data ?? [], null);
        $this->setIfExists('is3dSecure', $data ?? [], null);
        $this->setIfExists('last4', $data ?? [], null);
        $this->setIfExists('method', $data ?? [], null);
        $this->setIfExists('segment', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['_3dSecureType'] === null) {
            $invalidProperties[] = "'_3dSecureType' can't be null";
        }
        if ($this->container['acquirer'] === null) {
            $invalidProperties[] = "'acquirer' can't be null";
        }
        if ($this->container['bin'] === null) {
            $invalidProperties[] = "'bin' can't be null";
        }
        if ($this->container['brand'] === null) {
            $invalidProperties[] = "'brand' can't be null";
        }
        if ($this->container['country'] === null) {
            $invalidProperties[] = "'country' can't be null";
        }
        if ($this->container['customerCountry'] === null) {
            $invalidProperties[] = "'customerCountry' can't be null";
        }
        if ($this->container['customerIp'] === null) {
            $invalidProperties[] = "'customerIp' can't be null";
        }
        if ($this->container['expMonth'] === null) {
            $invalidProperties[] = "'expMonth' can't be null";
        }
        if ($this->container['expYear'] === null) {
            $invalidProperties[] = "'expYear' can't be null";
        }
        if ($this->container['is3dSecure'] === null) {
            $invalidProperties[] = "'is3dSecure' can't be null";
        }
        if ($this->container['last4'] === null) {
            $invalidProperties[] = "'last4' can't be null";
        }
        if ($this->container['method'] === null) {
            $invalidProperties[] = "'method' can't be null";
        }
        if ($this->container['segment'] === null) {
            $invalidProperties[] = "'segment' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets _3dSecureType
     *
     * @return string
     */
    public function get3dSecureType()
    {
        return $this->container['_3dSecureType'];
    }

    /**
     * Sets _3dSecureType
     *
     * @param string $_3dSecureType _3dSecureType
     *
     * @return self
     */
    public function set3dSecureType($_3dSecureType)
    {
        if (is_null($_3dSecureType)) {
            throw new \InvalidArgumentException('non-nullable _3dSecureType cannot be null');
        }
        $this->container['_3dSecureType'] = $_3dSecureType;

        return $this;
    }

    /**
     * Gets acquirer
     *
     * @return string
     */
    public function getAcquirer()
    {
        return $this->container['acquirer'];
    }

    /**
     * Sets acquirer
     *
     * @param string $acquirer acquirer
     *
     * @return self
     */
    public function setAcquirer($acquirer)
    {
        if (is_null($acquirer)) {
            throw new \InvalidArgumentException('non-nullable acquirer cannot be null');
        }
        $this->container['acquirer'] = $acquirer;

        return $this;
    }

    /**
     * Gets bin
     *
     * @return string
     */
    public function getBin()
    {
        return $this->container['bin'];
    }

    /**
     * Sets bin
     *
     * @param string $bin bin
     *
     * @return self
     */
    public function setBin($bin)
    {
        if (is_null($bin)) {
            throw new \InvalidArgumentException('non-nullable bin cannot be null');
        }
        $this->container['bin'] = $bin;

        return $this;
    }

    /**
     * Gets brand
     *
     * @return string
     */
    public function getBrand()
    {
        return $this->container['brand'];
    }

    /**
     * Sets brand
     *
     * @param string $brand brand
     *
     * @return self
     */
    public function setBrand($brand)
    {
        if (is_null($brand)) {
            throw new \InvalidArgumentException('non-nullable brand cannot be null');
        }
        $this->container['brand'] = $brand;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string $country country
     *
     * @return self
     */
    public function setCountry($country)
    {
        if (is_null($country)) {
            throw new \InvalidArgumentException('non-nullable country cannot be null');
        }
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets customerCountry
     *
     * @return string
     */
    public function getCustomerCountry()
    {
        return $this->container['customerCountry'];
    }

    /**
     * Sets customerCountry
     *
     * @param string $customerCountry customerCountry
     *
     * @return self
     */
    public function setCustomerCountry($customerCountry)
    {
        if (is_null($customerCountry)) {
            throw new \InvalidArgumentException('non-nullable customerCountry cannot be null');
        }
        $this->container['customerCountry'] = $customerCountry;

        return $this;
    }

    /**
     * Gets customerIp
     *
     * @return string
     */
    public function getCustomerIp()
    {
        return $this->container['customerIp'];
    }

    /**
     * Sets customerIp
     *
     * @param string $customerIp customerIp
     *
     * @return self
     */
    public function setCustomerIp($customerIp)
    {
        if (is_null($customerIp)) {
            throw new \InvalidArgumentException('non-nullable customerIp cannot be null');
        }
        $this->container['customerIp'] = $customerIp;

        return $this;
    }

    /**
     * Gets expMonth
     *
     * @return string
     */
    public function getExpMonth()
    {
        return $this->container['expMonth'];
    }

    /**
     * Sets expMonth
     *
     * @param string $expMonth expMonth
     *
     * @return self
     */
    public function setExpMonth($expMonth)
    {
        if (is_null($expMonth)) {
            throw new \InvalidArgumentException('non-nullable expMonth cannot be null');
        }
        $this->container['expMonth'] = $expMonth;

        return $this;
    }

    /**
     * Gets expYear
     *
     * @return string
     */
    public function getExpYear()
    {
        return $this->container['expYear'];
    }

    /**
     * Sets expYear
     *
     * @param string $expYear expYear
     *
     * @return self
     */
    public function setExpYear($expYear)
    {
        if (is_null($expYear)) {
            throw new \InvalidArgumentException('non-nullable expYear cannot be null');
        }
        $this->container['expYear'] = $expYear;

        return $this;
    }

    /**
     * Gets is3dSecure
     *
     * @return bool
     */
    public function getIs3dSecure()
    {
        return $this->container['is3dSecure'];
    }

    /**
     * Sets is3dSecure
     *
     * @param bool $is3dSecure is3dSecure
     *
     * @return self
     */
    public function setIs3dSecure($is3dSecure)
    {
        if (is_null($is3dSecure)) {
            throw new \InvalidArgumentException('non-nullable is3dSecure cannot be null');
        }
        $this->container['is3dSecure'] = $is3dSecure;

        return $this;
    }

    /**
     * Gets last4
     *
     * @return string
     */
    public function getLast4()
    {
        return $this->container['last4'];
    }

    /**
     * Sets last4
     *
     * @param string $last4 last4
     *
     * @return self
     */
    public function setLast4($last4)
    {
        if (is_null($last4)) {
            throw new \InvalidArgumentException('non-nullable last4 cannot be null');
        }
        $this->container['last4'] = $last4;

        return $this;
    }

    /**
     * Gets method
     *
     * @return string
     */
    public function getMethod()
    {
        return $this->container['method'];
    }

    /**
     * Sets method
     *
     * @param string $method method
     *
     * @return self
     */
    public function setMethod($method)
    {
        if (is_null($method)) {
            throw new \InvalidArgumentException('non-nullable method cannot be null');
        }
        $this->container['method'] = $method;

        return $this;
    }

    /**
     * Gets segment
     *
     * @return string
     */
    public function getSegment()
    {
        return $this->container['segment'];
    }

    /**
     * Sets segment
     *
     * @param string $segment segment
     *
     * @return self
     */
    public function setSegment($segment)
    {
        if (is_null($segment)) {
            throw new \InvalidArgumentException('non-nullable segment cannot be null');
        }
        $this->container['segment'] = $segment;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


