<?php
/**
 * SettlementFees
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Pensopay\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payment API
 *
 * Create and manage your Payments
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@pensopay.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Pensopay\Client\Model;

use \ArrayAccess;
use \Pensopay\Client\ObjectSerializer;

/**
 * SettlementFees Class Doc Comment
 *
 * @category Class
 * @description 
 * @package  Pensopay\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SettlementFees implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SettlementFees';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'sales' => 'int',
        'refunds' => 'int',
        'authorisations' => 'int',
        'credits' => 'int',
        'interchange' => 'int',
        'scheme' => 'int',
        'minimumProcessing' => 'int',
        'service' => 'int',
        'wireTransfer' => 'int',
        'chargebacks' => 'int',
        'retrievalRequests' => 'int',
        'series' => 'int',
        '_3dsecure' => 'int',
        'lateCapture' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'sales' => null,
        'refunds' => null,
        'authorisations' => null,
        'credits' => null,
        'interchange' => null,
        'scheme' => null,
        'minimumProcessing' => null,
        'service' => null,
        'wireTransfer' => null,
        'chargebacks' => null,
        'retrievalRequests' => null,
        'series' => null,
        '_3dsecure' => null,
        'lateCapture' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'sales' => false,
        'refunds' => false,
        'authorisations' => false,
        'credits' => false,
        'interchange' => false,
        'scheme' => false,
        'minimumProcessing' => false,
        'service' => false,
        'wireTransfer' => false,
        'chargebacks' => false,
        'retrievalRequests' => false,
        'series' => false,
        '_3dsecure' => false,
        'lateCapture' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'sales' => 'sales',
        'refunds' => 'refunds',
        'authorisations' => 'authorisations',
        'credits' => 'credits',
        'interchange' => 'interchange',
        'scheme' => 'scheme',
        'minimumProcessing' => 'minimum_processing',
        'service' => 'service',
        'wireTransfer' => 'wire_transfer',
        'chargebacks' => 'chargebacks',
        'retrievalRequests' => 'retrieval_requests',
        'series' => 'series',
        '_3dsecure' => '3dsecure',
        'lateCapture' => 'late_capture'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'sales' => 'setSales',
        'refunds' => 'setRefunds',
        'authorisations' => 'setAuthorisations',
        'credits' => 'setCredits',
        'interchange' => 'setInterchange',
        'scheme' => 'setScheme',
        'minimumProcessing' => 'setMinimumProcessing',
        'service' => 'setService',
        'wireTransfer' => 'setWireTransfer',
        'chargebacks' => 'setChargebacks',
        'retrievalRequests' => 'setRetrievalRequests',
        'series' => 'setSeries',
        '_3dsecure' => 'set3dsecure',
        'lateCapture' => 'setLateCapture'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'sales' => 'getSales',
        'refunds' => 'getRefunds',
        'authorisations' => 'getAuthorisations',
        'credits' => 'getCredits',
        'interchange' => 'getInterchange',
        'scheme' => 'getScheme',
        'minimumProcessing' => 'getMinimumProcessing',
        'service' => 'getService',
        'wireTransfer' => 'getWireTransfer',
        'chargebacks' => 'getChargebacks',
        'retrievalRequests' => 'getRetrievalRequests',
        'series' => 'getSeries',
        '_3dsecure' => 'get3dsecure',
        'lateCapture' => 'getLateCapture'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('sales', $data ?? [], null);
        $this->setIfExists('refunds', $data ?? [], null);
        $this->setIfExists('authorisations', $data ?? [], null);
        $this->setIfExists('credits', $data ?? [], null);
        $this->setIfExists('interchange', $data ?? [], null);
        $this->setIfExists('scheme', $data ?? [], null);
        $this->setIfExists('minimumProcessing', $data ?? [], null);
        $this->setIfExists('service', $data ?? [], null);
        $this->setIfExists('wireTransfer', $data ?? [], null);
        $this->setIfExists('chargebacks', $data ?? [], null);
        $this->setIfExists('retrievalRequests', $data ?? [], null);
        $this->setIfExists('series', $data ?? [], null);
        $this->setIfExists('_3dsecure', $data ?? [], null);
        $this->setIfExists('lateCapture', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets sales
     *
     * @return int|null
     */
    public function getSales()
    {
        return $this->container['sales'];
    }

    /**
     * Sets sales
     *
     * @param int|null $sales 
     *
     * @return self
     */
    public function setSales($sales)
    {
        if (is_null($sales)) {
            throw new \InvalidArgumentException('non-nullable sales cannot be null');
        }
        $this->container['sales'] = $sales;

        return $this;
    }

    /**
     * Gets refunds
     *
     * @return int|null
     */
    public function getRefunds()
    {
        return $this->container['refunds'];
    }

    /**
     * Sets refunds
     *
     * @param int|null $refunds 
     *
     * @return self
     */
    public function setRefunds($refunds)
    {
        if (is_null($refunds)) {
            throw new \InvalidArgumentException('non-nullable refunds cannot be null');
        }
        $this->container['refunds'] = $refunds;

        return $this;
    }

    /**
     * Gets authorisations
     *
     * @return int|null
     */
    public function getAuthorisations()
    {
        return $this->container['authorisations'];
    }

    /**
     * Sets authorisations
     *
     * @param int|null $authorisations 
     *
     * @return self
     */
    public function setAuthorisations($authorisations)
    {
        if (is_null($authorisations)) {
            throw new \InvalidArgumentException('non-nullable authorisations cannot be null');
        }
        $this->container['authorisations'] = $authorisations;

        return $this;
    }

    /**
     * Gets credits
     *
     * @return int|null
     */
    public function getCredits()
    {
        return $this->container['credits'];
    }

    /**
     * Sets credits
     *
     * @param int|null $credits 
     *
     * @return self
     */
    public function setCredits($credits)
    {
        if (is_null($credits)) {
            throw new \InvalidArgumentException('non-nullable credits cannot be null');
        }
        $this->container['credits'] = $credits;

        return $this;
    }

    /**
     * Gets interchange
     *
     * @return int|null
     */
    public function getInterchange()
    {
        return $this->container['interchange'];
    }

    /**
     * Sets interchange
     *
     * @param int|null $interchange 
     *
     * @return self
     */
    public function setInterchange($interchange)
    {
        if (is_null($interchange)) {
            throw new \InvalidArgumentException('non-nullable interchange cannot be null');
        }
        $this->container['interchange'] = $interchange;

        return $this;
    }

    /**
     * Gets scheme
     *
     * @return int|null
     */
    public function getScheme()
    {
        return $this->container['scheme'];
    }

    /**
     * Sets scheme
     *
     * @param int|null $scheme 
     *
     * @return self
     */
    public function setScheme($scheme)
    {
        if (is_null($scheme)) {
            throw new \InvalidArgumentException('non-nullable scheme cannot be null');
        }
        $this->container['scheme'] = $scheme;

        return $this;
    }

    /**
     * Gets minimumProcessing
     *
     * @return int|null
     */
    public function getMinimumProcessing()
    {
        return $this->container['minimumProcessing'];
    }

    /**
     * Sets minimumProcessing
     *
     * @param int|null $minimumProcessing 
     *
     * @return self
     */
    public function setMinimumProcessing($minimumProcessing)
    {
        if (is_null($minimumProcessing)) {
            throw new \InvalidArgumentException('non-nullable minimumProcessing cannot be null');
        }
        $this->container['minimumProcessing'] = $minimumProcessing;

        return $this;
    }

    /**
     * Gets service
     *
     * @return int|null
     */
    public function getService()
    {
        return $this->container['service'];
    }

    /**
     * Sets service
     *
     * @param int|null $service 
     *
     * @return self
     */
    public function setService($service)
    {
        if (is_null($service)) {
            throw new \InvalidArgumentException('non-nullable service cannot be null');
        }
        $this->container['service'] = $service;

        return $this;
    }

    /**
     * Gets wireTransfer
     *
     * @return int|null
     */
    public function getWireTransfer()
    {
        return $this->container['wireTransfer'];
    }

    /**
     * Sets wireTransfer
     *
     * @param int|null $wireTransfer 
     *
     * @return self
     */
    public function setWireTransfer($wireTransfer)
    {
        if (is_null($wireTransfer)) {
            throw new \InvalidArgumentException('non-nullable wireTransfer cannot be null');
        }
        $this->container['wireTransfer'] = $wireTransfer;

        return $this;
    }

    /**
     * Gets chargebacks
     *
     * @return int|null
     */
    public function getChargebacks()
    {
        return $this->container['chargebacks'];
    }

    /**
     * Sets chargebacks
     *
     * @param int|null $chargebacks 
     *
     * @return self
     */
    public function setChargebacks($chargebacks)
    {
        if (is_null($chargebacks)) {
            throw new \InvalidArgumentException('non-nullable chargebacks cannot be null');
        }
        $this->container['chargebacks'] = $chargebacks;

        return $this;
    }

    /**
     * Gets retrievalRequests
     *
     * @return int|null
     */
    public function getRetrievalRequests()
    {
        return $this->container['retrievalRequests'];
    }

    /**
     * Sets retrievalRequests
     *
     * @param int|null $retrievalRequests 
     *
     * @return self
     */
    public function setRetrievalRequests($retrievalRequests)
    {
        if (is_null($retrievalRequests)) {
            throw new \InvalidArgumentException('non-nullable retrievalRequests cannot be null');
        }
        $this->container['retrievalRequests'] = $retrievalRequests;

        return $this;
    }

    /**
     * Gets series
     *
     * @return int|null
     */
    public function getSeries()
    {
        return $this->container['series'];
    }

    /**
     * Sets series
     *
     * @param int|null $series 
     *
     * @return self
     */
    public function setSeries($series)
    {
        if (is_null($series)) {
            throw new \InvalidArgumentException('non-nullable series cannot be null');
        }
        $this->container['series'] = $series;

        return $this;
    }

    /**
     * Gets _3dsecure
     *
     * @return int|null
     */
    public function get3dsecure()
    {
        return $this->container['_3dsecure'];
    }

    /**
     * Sets _3dsecure
     *
     * @param int|null $_3dsecure 
     *
     * @return self
     */
    public function set3dsecure($_3dsecure)
    {
        if (is_null($_3dsecure)) {
            throw new \InvalidArgumentException('non-nullable _3dsecure cannot be null');
        }
        $this->container['_3dsecure'] = $_3dsecure;

        return $this;
    }

    /**
     * Gets lateCapture
     *
     * @return int|null
     */
    public function getLateCapture()
    {
        return $this->container['lateCapture'];
    }

    /**
     * Sets lateCapture
     *
     * @param int|null $lateCapture 
     *
     * @return self
     */
    public function setLateCapture($lateCapture)
    {
        if (is_null($lateCapture)) {
            throw new \InvalidArgumentException('non-nullable lateCapture cannot be null');
        }
        $this->container['lateCapture'] = $lateCapture;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


