<?php
/**
 * FeesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  PensoPay\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payment API
 *
 * Create and manage your Payments
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@pensopay.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace PensoPay\Client\Test\Api;

use \PensoPay\Client\Configuration;
use \PensoPay\Client\ApiException;
use \PensoPay\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FeesApiTest Class Doc Comment
 *
 * @category Class
 * @package  PensoPay\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FeesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createANewFee
     *
     * Create a new fee.
     *
     */
    public function testCreateANewFee()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteAFee
     *
     * Delete a fee.
     *
     */
    public function testDeleteAFee()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAFee
     *
     * Get a single fee.
     *
     */
    public function testGetAFee()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAListOfFees
     *
     * Get auto-fees configured for account.
     *
     */
    public function testGetAListOfFees()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for testFees
     *
     * Test fees for account.
     *
     */
    public function testTestFees()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateAFee
     *
     * Update a fee.
     *
     */
    public function testUpdateAFee()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
