<?php
/**
 * MethodsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  PensoPay\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payment API
 *
 * Create and manage your Payments
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@pensopay.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace PensoPay\Client\Test\Api;

use \PensoPay\Client\Configuration;
use \PensoPay\Client\ApiException;
use \PensoPay\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MethodsApiTest Class Doc Comment
 *
 * @category Class
 * @package  PensoPay\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MethodsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getMethods
     *
     * Get methods for account.
     *
     */
    public function testGetMethods()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMobilepayLogo
     *
     * Get account logo.
     *
     */
    public function testGetMobilepayLogo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for putMobilepayLogo
     *
     * Upload account logo.
     *
     */
    public function testPutMobilepayLogo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
