<?php
/**
 * SettlementApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Pensopay\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payment API
 *
 * Create and manage your Payments
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@pensopay.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Pensopay\Client\Test\Api;

use \Pensopay\Client\Configuration;
use \Pensopay\Client\ApiException;
use \Pensopay\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SettlementApiTest Class Doc Comment
 *
 * @category Class
 * @package  Pensopay\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SettlementApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getSettlement
     *
     * Get Settlement.
     *
     */
    public function testGetSettlement()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSettlements
     *
     * Get settlements.
     *
     */
    public function testGetSettlements()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTransactionsBySettlement
     *
     * Get Settlement Transactions.
     *
     */
    public function testGetTransactionsBySettlement()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
